#!/bin/bash
# try hostname
eval USE=$(awk '/#/{next}HH=="'$(hostname)'"{print $2;exit}' compiler-list)

# try domainname
[[ -z $USE ]]&&
eval USE=$(awk '/#/{next}/^\*\.'$(domainname)'/{print $2;exit}' compiler-list)

# default
[[ -z $USE ]]&&
eval USE=$(awk '$1=="*"{print $2}' compiler-list)

echo $USE
