#!/bin/bash

make clean
cat << endt > machine
$(hostname)
$(hostname)
$(hostname)
$(hostname)
endt

EXE=lenjo

export OMD_TABLE=$HOME/omd-tables
make &&
#nohup mpirun -machinefile machine -np 4 $EXE $@ 2>err &
mpirun -machinefile machine -np 2 $EXE 2>err
